postgres_user:
  database: smartnode
  user: smartnode
  password: cohLaich2uo9loZ
  host: localhost
  port: 5432
  minsize: 1
  maxsize: 5
postgres_admin:
  database: postgres
  user: postgres
  password: postgres
  host: localhost
  port: 5432
  minsize: 1
  maxsize: 5